# Generated by Django 3.2.7 on 2021-09-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezbook_project', '0002_auto_20210915_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_pic',
            field=models.CharField(default='noimage.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_pic',
            field=models.CharField(default='noimage.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_pic',
            field=models.CharField(default='noimage.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_pic',
            field=models.CharField(default='noimage.png', max_length=100),
        ),
    ]
